name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: AOSCOSLauncher.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  BUILD_PLATFORM: x64|ARM64
  APPX_PACKAGE_DIR: AppxPackages
  X64_TAR_FILE_ADDRESS: https://releases.aosc.io/os-amd64/container/aosc-os_container_20210602_amd64.tar.xz
  X64_TAR_FILE_HASH: 975a21b5a1a27ff97a142494ec15cb6566ecce2572046704c89e3d8a4a297ddb
  ARM64_TAR_FILE_ADDRESS: https://releases.aosc.io/os-arm64/container/aosc-os_container_20210602_arm64.tar.xz
  ARM64_TAR_FILE_HASH: 88bdea5f6a533d1635d9f9f697917c5e9c7f86c211965e4279d5644e343d5e52

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-prerelease: true
            
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Download tar files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        New-Item -Path x64 -ItemType Directory
        Invoke-WebRequest -Uri ${{env.X64_TAR_FILE_ADDRESS}} -OutFile x64\install.tar.gz
        if ((Get-FileHash -Path .\x64\install.tar.gz).Hash -ne "${{env.X64_TAR_FILE_HASH}}") {throw "x64 tar file hash not match."}
        New-Item -Path ARM64 -ItemType Directory
        Invoke-WebRequest -Uri ${{env.ARM64_TAR_FILE_ADDRESS}} -OutFile ARM64\install.tar.gz
        if ((Get-FileHash -Path .\ARM64\install.tar.gz).Hash -ne "${{env.ARM64_TAR_FILE_HASH}}") {throw "ARM64 tar file hash not match."}
      shell: pwsh

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:AppxBundlePlatforms=${{env.BUILD_PLATFORM}} /p:AppxPackageDir=${{env.APPX_PACKAGE_DIR}} /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload ${{env.SOLUTION_FILE_PATH}}
